<?php declare(strict_types=1);

// Czech translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Vygenerováno pomocí Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'page' => 'Strana',

	// Document Types
	'invoice' => 'FAKTURA',
	'proforma_invoice' => 'PROFORMA FAKTURA',
	'invoice_header_taxpayer' => 'FAKTURA - Daňový doklad č. ',
	'invoice_header_non_taxpayer' => 'FAKTURA č. ',
	'proforma_invoice_header' => 'PROFORMA FAKTURA č. ',
	'corrective_document_header' => 'OPRAVNÝ DAŇOVÝ DOKLAD č. ',
	'credit_note' => 'DOBROPIS',
	'credit_note_header' => 'DOBROPIS č. ',
	'cancelled' => 'STORNO',
	'cancelled_invoice_header' => 'STORNO FAKTURA č. ',
	'cancelled_invoice_header_taxpayer' => 'STORNO FAKTURA - Daňový doklad č. ',

	// Document References
	'corrective_document_for_invoice' => 'Opravný daňový doklad k faktuře č. ',
	'credit_note_for_invoice' => 'Dobropis k faktuře č. ',
	'cancellation_for_invoice' => 'Storno k faktuře č. ',
	'correction_reason' => 'Důvod opravy: ',

	// Parties
	'supplier' => 'Dodavatel',
	'customer' => 'Odběratel',
	'end_recipient' => 'Konečný příjemce',

	// Contact Info
	'company_id' => 'IČ:',
	'vat_id' => 'DIČ:',
	'email' => 'E-mail:',
	'phone' => 'Tel.:',
	'website' => 'Web:',
	'default_country' => 'Česká republika',

	// Dates
	'issue_date' => 'Datum vystavení:',
	'due_date' => 'Datum splatnosti:',
	'tax_point_date' => 'Datum zdanitelného plnění:',
	'from_date' => 'Ze dne:',
	'date_and_time' => 'Datum a čas',

	// Order Reference
	'based_on_order_no' => 'Na základě objednávky č.:',

	// Payment Info
	'payment_details' => 'Platební údaje',
	'payment_method' => 'Způsob úhrady:',
	'account_number' => 'Číslo účtu:',
	'bank_code' => 'Kód banky:',
	'variable_symbol' => 'Variabilní symbol:',
	'constant_symbol' => 'Konstantní symbol:',
	'specific_symbol' => 'Specifický symbol:',
	'qr_payment' => 'QR platba',

	// Items Table
	'items_to_pay' => 'Položky k úhradě',
	'item' => 'Položka',
	'item_name' => 'Název položky',
	'quantity' => 'Počet M.J.',
	'unit' => 'M.J.',
	'price' => 'Cena',
	'unit_price' => 'Cena za M.J.',
	'total_price' => 'Cena celkem',

	// Tax Calculations
	'vat' => 'DPH',
	'vat_rate' => 'DPH %',
	'excl_vat' => 'bez DPH',
	'incl_vat' => 's DPH',
	'vat_amount' => 'Výše DPH',
	'tax_base' => 'Základ',

	// Totals Summary
	'total' => 'Celkem',
	'total_final' => 'CELKEM',
	'items_subtotal' => 'Součet položek',
	'total_to_pay' => 'CELKEM K ÚHRADĚ:',
	'discount' => 'Sleva:',
	'discount_rounded' => 'Sleva (zaokrouhleno):',
	'rounding' => 'Zaokrouhlení',
	'rounding_in_rate' => 'Zaokrouhlení v sazbě ',
	'including_rounding' => 'Částky jsou včetně hodnot zaokrouhlení',
	'paid_advances' => 'Uhrazené zálohy:',
	'already_paid_do_not_pay' => 'JIŽ UHRAZENO - NEPLATIT',

	// Footer Signature
	'stamp_and_signature' => 'Razítko, podpis dodavatele',

	// Additional Info
	'additional_information' => 'Doplňující informace:',

	// Tax Regime
	'reverse_charge_notice' => 'Faktura je v režimu přenesené daňové povinnosti podle § 92e zákona o DPH, kdy výši daně je povinen doplnit a přiznat plátce, pro kterého je plnění uskutečněno.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Elektronická evidence tržeb:',
	'establishment' => 'Provozovna',
	'cash_register' => 'Pokladna',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Režim',
];
