<?php declare(strict_types=1);

// German translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Erstellt mit Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'footer_middle_text' => 'faktury.chci-www.cz',
	'page' => 'Seite',

	// Document Types
	'invoice' => 'RECHNUNG',
	'proforma_invoice' => 'PROFORMA-RECHNUNG',
	'invoice_header_taxpayer' => 'RECHNUNG - Steuerbeleg Nr. ',
	'invoice_header_non_taxpayer' => 'RECHNUNG Nr. ',
	'proforma_invoice_header' => 'PROFORMA-RECHNUNG Nr. ',
	'corrective_document_header' => 'KORREKTURBELEG Nr. ',
	'credit_note' => 'GUTSCHRIFT',
	'credit_note_header' => 'GUTSCHRIFT Nr. ',
	'cancelled' => 'STORNIERT',
	'cancelled_invoice_header' => 'STORNIERTE RECHNUNG Nr. ',
	'cancelled_invoice_header_taxpayer' => 'STORNIERTE RECHNUNG - Steuerbeleg Nr. ',

	// Document References
	'corrective_document_for_invoice' => 'Korrekturbeleg zur Rechnung Nr. ',
	'credit_note_for_invoice' => 'Gutschrift zur Rechnung Nr. ',
	'cancellation_for_invoice' => 'Stornierung zur Rechnung Nr. ',
	'correction_reason' => 'Korrekturgrund: ',

	// Parties
	'supplier' => 'Lieferant',
	'customer' => 'Kunde',
	'end_recipient' => 'Endempfänger',

	// Contact Info
	'company_id' => 'Handelsreg.-Nr.:',
	'vat_id' => 'USt-IdNr.:',
	'email' => 'E-Mail:',
	'phone' => 'Tel.:',
	'website' => 'Web:',
	'default_country' => 'Deutschland',

	// Dates
	'issue_date' => 'Ausstellungsdatum:',
	'due_date' => 'Fälligkeitsdatum:',
	'tax_point_date' => 'Leistungsdatum:',
	'from_date' => 'Vom:',
	'date_and_time' => 'Datum und Uhrzeit',

	// Order Reference
	'based_on_order_no' => 'Basierend auf Bestellung Nr.:',

	// Payment Info
	'payment_details' => 'Zahlungsinformationen',
	'payment_method' => 'Zahlungsart:',
	'account_number' => 'Kontonummer:',
	'bank_code' => 'Bankleitzahl:',
	'variable_symbol' => 'Verwendungszweck:',
	'constant_symbol' => 'Konstantsymbol:',
	'specific_symbol' => 'Spezifisches Symbol:',
	'qr_payment' => 'QR-Zahlung',

	// Items Table
	'items_to_pay' => 'Rechnungspositionen',
	'item' => 'Position',
	'item_name' => 'Bezeichnung',
	'quantity' => 'Menge',
	'unit' => 'Einheit',
	'price' => 'Preis',
	'unit_price' => 'Einzelpreis',
	'total_price' => 'Gesamtpreis',

	// Tax Calculations
	'vat' => 'MwSt.',
	'vat_rate' => 'MwSt. %',
	'excl_vat' => 'ohne MwSt.',
	'incl_vat' => 'inkl. MwSt.',
	'vat_amount' => 'MwSt.-Betrag',
	'tax_base' => 'Nettobetrag',

	// Totals Summary
	'total' => 'Gesamt',
	'total_final' => 'GESAMT',
	'items_subtotal' => 'Zwischensumme',
	'total_to_pay' => 'ZU ZAHLENDER BETRAG:',
	'discount' => 'Rabatt:',
	'discount_rounded' => 'Rabatt (gerundet):',
	'rounding' => 'Rundung',
	'rounding_in_rate' => 'Rundung im Satz ',
	'including_rounding' => 'Beträge enthalten Rundungswerte',
	'paid_advances' => 'Bezahlte Anzahlungen:',
	'already_paid_do_not_pay' => 'BEREITS BEZAHLT - NICHT ZAHLEN',

	// Footer Signature
	'stamp_and_signature' => 'Stempel und Unterschrift des Lieferanten',

	// Additional Info
	'additional_information' => 'Zusätzliche Informationen:',

	// Tax Regime
	'reverse_charge_notice' => 'Diese Rechnung unterliegt dem Reverse-Charge-Verfahren gemäß § 13b UStG. Die Umsatzsteuer ist vom Leistungsempfänger zu berechnen und abzuführen.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Elektronische Umsatzerfassung:',
	'establishment' => 'Betriebsstätte',
	'cash_register' => 'Kasse',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Modus',
];
