<?php declare(strict_types=1);

// English translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Generated using Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'page' => 'Page',

	// Document Types
	'invoice' => 'INVOICE',
	'proforma_invoice' => 'PROFORMA INVOICE',
	'invoice_header_taxpayer' => 'INVOICE - Tax document No. ',
	'invoice_header_non_taxpayer' => 'INVOICE No. ',
	'proforma_invoice_header' => 'PROFORMA INVOICE No. ',
	'corrective_document_header' => 'CORRECTIVE TAX DOCUMENT No. ',
	'credit_note' => 'CREDIT NOTE',
	'credit_note_header' => 'CREDIT NOTE No. ',
	'cancelled' => 'CANCELLED',
	'cancelled_invoice_header' => 'CANCELLED INVOICE No. ',
	'cancelled_invoice_header_taxpayer' => 'CANCELLED INVOICE - Tax document No. ',

	// Document References
	'corrective_document_for_invoice' => 'Corrective tax document for invoice No. ',
	'credit_note_for_invoice' => 'Credit note for invoice No. ',
	'cancellation_for_invoice' => 'Cancellation for invoice No. ',
	'correction_reason' => 'Reason for correction: ',

	// Parties
	'supplier' => 'Supplier',
	'customer' => 'Customer',
	'end_recipient' => 'End recipient',

	// Contact Info
	'company_id' => 'ID:',
	'vat_id' => 'VAT ID:',
	'email' => 'E-mail:',
	'phone' => 'Phone:',
	'website' => 'Web:',
	'default_country' => 'Czech Republic',

	// Dates
	'issue_date' => 'Issue date:',
	'due_date' => 'Due date:',
	'tax_point_date' => 'Tax point date:',
	'from_date' => 'From date:',
	'date_and_time' => 'Date and time',

	// Order Reference
	'based_on_order_no' => 'Based on order No.:',

	// Payment Info
	'payment_details' => 'Payment details',
	'payment_method' => 'Payment method:',
	'account_number' => 'Account number:',
	'bank_code' => 'Bank code:',
	'variable_symbol' => 'Variable symbol:',
	'constant_symbol' => 'Constant symbol:',
	'specific_symbol' => 'Specific symbol:',
	'qr_payment' => 'QR payment',

	// Items Table
	'items_to_pay' => 'Items to pay',
	'item' => 'Item',
	'item_name' => 'Item name',
	'quantity' => 'Qty',
	'unit' => 'Unit',
	'price' => 'Price',
	'unit_price' => 'Unit price',
	'total_price' => 'Total price',

	// Tax Calculations
	'vat' => 'VAT',
	'vat_rate' => 'VAT %',
	'excl_vat' => 'excl. VAT',
	'incl_vat' => 'incl. VAT',
	'vat_amount' => 'VAT amount',
	'tax_base' => 'Base',

	// Totals Summary
	'total' => 'Total',
	'total_final' => 'TOTAL',
	'items_subtotal' => 'Sum of items',
	'total_to_pay' => 'TOTAL TO PAY:',
	'discount' => 'Discount:',
	'discount_rounded' => 'Discount (rounded):',
	'rounding' => 'Rounding',
	'rounding_in_rate' => 'Rounding in rate ',
	'including_rounding' => 'Amounts include rounding values',
	'paid_advances' => 'Paid advances:',
	'already_paid_do_not_pay' => 'ALREADY PAID - DO NOT PAY',

	// Footer Signature
	'stamp_and_signature' => 'Stamp and signature of supplier',

	// Additional Info
	'additional_information' => 'Additional information:',

	// Tax Regime
	'reverse_charge_notice' => 'This invoice is issued under the reverse charge regime according to § 92e of the VAT Act, where the VAT amount must be filled in and declared by the taxpayer for whom the service is provided.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Electronic evidence of sales:',
	'establishment' => 'Establishment',
	'cash_register' => 'Cash register',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Mode',
];
