<?php declare(strict_types=1);

// Hungarian translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Készítette: Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'footer_middle_text' => 'faktury.chci-www.cz',
	'page' => 'Oldal',

	// Document Types
	'invoice' => 'SZÁMLA',
	'proforma_invoice' => 'DÍJBEKÉRŐ',
	'invoice_header_taxpayer' => 'SZÁMLA - Adóbizonylat sz. ',
	'invoice_header_non_taxpayer' => 'SZÁMLA sz. ',
	'proforma_invoice_header' => 'DÍJBEKÉRŐ sz. ',
	'corrective_document_header' => 'HELYESBÍTŐ SZÁMLA sz. ',
	'credit_note' => 'JÓVÁÍRÁS',
	'credit_note_header' => 'JÓVÁÍRÁS sz. ',
	'cancelled' => 'SZTORNÓZOTT',
	'cancelled_invoice_header' => 'SZTORNÓ SZÁMLA sz. ',
	'cancelled_invoice_header_taxpayer' => 'SZTORNÓ SZÁMLA - Adóbizonylat sz. ',

	// Document References
	'corrective_document_for_invoice' => 'Helyesbítő számla a számla sz. ',
	'credit_note_for_invoice' => 'Jóváírás a számla sz. ',
	'cancellation_for_invoice' => 'Sztornó a számla sz. ',
	'correction_reason' => 'Helyesbítés oka: ',

	// Parties
	'supplier' => 'Szállító',
	'customer' => 'Vevő',
	'end_recipient' => 'Végső címzett',

	// Contact Info
	'company_id' => 'Cégjegyzékszám:',
	'vat_id' => 'Adószám:',
	'email' => 'E-mail:',
	'phone' => 'Tel.:',
	'website' => 'Web:',
	'default_country' => 'Magyarország',

	// Dates
	'issue_date' => 'Kiállítás dátuma:',
	'due_date' => 'Fizetési határidő:',
	'tax_point_date' => 'Teljesítés dátuma:',
	'from_date' => 'Keltezés:',
	'date_and_time' => 'Dátum és idő',

	// Order Reference
	'based_on_order_no' => 'Megrendelés alapján sz.:',

	// Payment Info
	'payment_details' => 'Fizetési adatok',
	'payment_method' => 'Fizetési mód:',
	'account_number' => 'Bankszámlaszám:',
	'bank_code' => 'Bank kód:',
	'variable_symbol' => 'Változó szimbólum:',
	'constant_symbol' => 'Állandó szimbólum:',
	'specific_symbol' => 'Specifikus szimbólum:',
	'qr_payment' => 'QR fizetés',

	// Items Table
	'items_to_pay' => 'Fizetendő tételek',
	'item' => 'Tétel',
	'item_name' => 'Megnevezés',
	'quantity' => 'Mennyiség',
	'unit' => 'Egység',
	'price' => 'Ár',
	'unit_price' => 'Egységár',
	'total_price' => 'Összesen',

	// Tax Calculations
	'vat' => 'ÁFA',
	'vat_rate' => 'ÁFA %',
	'excl_vat' => 'nettó',
	'incl_vat' => 'bruttó',
	'vat_amount' => 'ÁFA összeg',
	'tax_base' => 'Adóalap',

	// Totals Summary
	'total' => 'Összesen',
	'total_final' => 'ÖSSZESEN',
	'items_subtotal' => 'Tételek összege',
	'total_to_pay' => 'FIZETENDŐ ÖSSZEG:',
	'discount' => 'Kedvezmény:',
	'discount_rounded' => 'Kedvezmény (kerekítve):',
	'rounding' => 'Kerekítés',
	'rounding_in_rate' => 'Kerekítés a ',
	'including_rounding' => 'Az összegek tartalmazzák a kerekítési értékeket',
	'paid_advances' => 'Befizetett előlegek:',
	'already_paid_do_not_pay' => 'KIFIZETVE - NE FIZESSEN',

	// Footer Signature
	'stamp_and_signature' => 'Szállító bélyegzője és aláírása',

	// Additional Info
	'additional_information' => 'További információk:',

	// Tax Regime
	'reverse_charge_notice' => 'Ez a számla a fordított adózás szabályai szerint készült az ÁFA törvény 142. § alapján. Az ÁFA bevallására és megfizetésére a vevő kötelezett.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Elektronikus értékesítési nyilvántartás:',
	'establishment' => 'Üzlet',
	'cash_register' => 'Pénztárgép',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Üzemmód',
];
