<?php declare(strict_types=1);

// Polish translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Wygenerowano za pomocą Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'footer_middle_text' => 'faktury.chci-www.cz',
	'page' => 'Strona',

	// Document Types
	'invoice' => 'FAKTURA',
	'proforma_invoice' => 'FAKTURA PROFORMA',
	'invoice_header_taxpayer' => 'FAKTURA VAT nr ',
	'invoice_header_non_taxpayer' => 'FAKTURA nr ',
	'proforma_invoice_header' => 'FAKTURA PROFORMA nr ',
	'corrective_document_header' => 'FAKTURA KORYGUJĄCA nr ',
	'credit_note' => 'NOTA KREDYTOWA',
	'credit_note_header' => 'NOTA KREDYTOWA nr ',
	'cancelled' => 'ANULOWANA',
	'cancelled_invoice_header' => 'FAKTURA ANULOWANA nr ',
	'cancelled_invoice_header_taxpayer' => 'FAKTURA VAT ANULOWANA nr ',

	// Document References
	'corrective_document_for_invoice' => 'Faktura korygująca do faktury nr ',
	'credit_note_for_invoice' => 'Nota kredytowa do faktury nr ',
	'cancellation_for_invoice' => 'Anulowanie faktury nr ',
	'correction_reason' => 'Przyczyna korekty: ',

	// Parties
	'supplier' => 'Sprzedawca',
	'customer' => 'Nabywca',
	'end_recipient' => 'Odbiorca końcowy',

	// Contact Info
	'company_id' => 'NIP:',
	'vat_id' => 'NIP UE:',
	'email' => 'E-mail:',
	'phone' => 'Tel.:',
	'website' => 'Web:',
	'default_country' => 'Polska',

	// Dates
	'issue_date' => 'Data wystawienia:',
	'due_date' => 'Termin płatności:',
	'tax_point_date' => 'Data sprzedaży:',
	'from_date' => 'Z dnia:',
	'date_and_time' => 'Data i godzina',

	// Order Reference
	'based_on_order_no' => 'Na podstawie zamówienia nr:',

	// Payment Info
	'payment_details' => 'Dane do płatności',
	'payment_method' => 'Forma płatności:',
	'account_number' => 'Numer konta:',
	'bank_code' => 'Kod banku:',
	'variable_symbol' => 'Symbol zmienny:',
	'constant_symbol' => 'Symbol stały:',
	'specific_symbol' => 'Symbol specyficzny:',
	'qr_payment' => 'Płatność QR',

	// Items Table
	'items_to_pay' => 'Pozycje do zapłaty',
	'item' => 'Pozycja',
	'item_name' => 'Nazwa pozycji',
	'quantity' => 'Ilość',
	'unit' => 'J.m.',
	'price' => 'Cena',
	'unit_price' => 'Cena jednostkowa',
	'total_price' => 'Wartość',

	// Tax Calculations
	'vat' => 'VAT',
	'vat_rate' => 'VAT %',
	'excl_vat' => 'netto',
	'incl_vat' => 'brutto',
	'vat_amount' => 'Kwota VAT',
	'tax_base' => 'Podstawa',

	// Totals Summary
	'total' => 'Razem',
	'total_final' => 'RAZEM',
	'items_subtotal' => 'Suma pozycji',
	'total_to_pay' => 'DO ZAPŁATY:',
	'discount' => 'Rabat:',
	'discount_rounded' => 'Rabat (zaokrąglony):',
	'rounding' => 'Zaokrąglenie',
	'rounding_in_rate' => 'Zaokrąglenie w stawce ',
	'including_rounding' => 'Kwoty zawierają wartości zaokrągleń',
	'paid_advances' => 'Wpłacone zaliczki:',
	'already_paid_do_not_pay' => 'ZAPŁACONO - NIE PŁACIĆ',

	// Footer Signature
	'stamp_and_signature' => 'Pieczątka i podpis sprzedawcy',

	// Additional Info
	'additional_information' => 'Informacje dodatkowe:',

	// Tax Regime
	'reverse_charge_notice' => 'Faktura wystawiona w procedurze odwrotnego obciążenia zgodnie z art. 17 ust. 1 pkt 7-8 ustawy o VAT. Podatek VAT rozlicza nabywca.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Elektroniczna ewidencja sprzedaży:',
	'establishment' => 'Punkt sprzedaży',
	'cash_register' => 'Kasa',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Tryb',
];
