<?php declare(strict_types=1);

// Slovak translations for invoice generator

return [
	// General / Metadata
	'generated_by' => 'Vygenerované pomocou Kenod\InvoiceGenerator Library',
	'generated_footer' => 'Generated by Kenod\InvoiceGenerator 3.0.0',
	'page' => 'Strana',

	// Document Types
	'invoice' => 'FAKTÚRA',
	'proforma_invoice' => 'PROFORMA FAKTÚRA',
	'invoice_header_taxpayer' => 'FAKTÚRA - Daňový doklad č. ',
	'invoice_header_non_taxpayer' => 'FAKTÚRA č. ',
	'proforma_invoice_header' => 'PROFORMA FAKTÚRA č. ',
	'corrective_document_header' => 'OPRAVNÝ DAŇOVÝ DOKLAD č. ',
	'credit_note' => 'DOBROPIS',
	'credit_note_header' => 'DOBROPIS č. ',
	'cancelled' => 'STORNO',
	'cancelled_invoice_header' => 'STORNO FAKTÚRA č. ',
	'cancelled_invoice_header_taxpayer' => 'STORNO FAKTÚRA - Daňový doklad č. ',

	// Document References
	'corrective_document_for_invoice' => 'Opravný daňový doklad k faktúre č. ',
	'credit_note_for_invoice' => 'Dobropis k faktúre č. ',
	'cancellation_for_invoice' => 'Storno k faktúre č. ',
	'correction_reason' => 'Dôvod opravy: ',

	// Parties
	'supplier' => 'Dodávateľ',
	'customer' => 'Odberateľ',
	'end_recipient' => 'Konečný prijímateľ',

	// Contact Info
	'company_id' => 'IČO:',
	'vat_id' => 'DIČ:',
	'email' => 'E-mail:',
	'phone' => 'Tel.:',
	'website' => 'Web:',
	'default_country' => 'Slovenská republika',

	// Dates
	'issue_date' => 'Dátum vystavenia:',
	'due_date' => 'Dátum splatnosti:',
	'tax_point_date' => 'Dátum zdaniteľného plnenia:',
	'from_date' => 'Zo dňa:',
	'date_and_time' => 'Dátum a čas',

	// Order Reference
	'based_on_order_no' => 'Na základe objednávky č.:',

	// Payment Info
	'payment_details' => 'Platobné údaje',
	'payment_method' => 'Spôsob úhrady:',
	'account_number' => 'Číslo účtu:',
	'bank_code' => 'Kód banky:',
	'variable_symbol' => 'Variabilný symbol:',
	'constant_symbol' => 'Konštantný symbol:',
	'specific_symbol' => 'Špecifický symbol:',
	'qr_payment' => 'QR platba',

	// Items Table
	'items_to_pay' => 'Položky k úhrade',
	'item' => 'Položka',
	'item_name' => 'Názov položky',
	'quantity' => 'Počet M.J.',
	'unit' => 'M.J.',
	'price' => 'Cena',
	'unit_price' => 'Cena za M.J.',
	'total_price' => 'Cena celkom',

	// Tax Calculations
	'vat' => 'DPH',
	'vat_rate' => 'DPH %',
	'excl_vat' => 'bez DPH',
	'incl_vat' => 's DPH',
	'vat_amount' => 'Výška DPH',
	'tax_base' => 'Základ',

	// Totals Summary
	'total' => 'Celkom',
	'total_final' => 'CELKOM',
	'items_subtotal' => 'Súčet položiek',
	'total_to_pay' => 'CELKOM K ÚHRADE:',
	'discount' => 'Zľava:',
	'discount_rounded' => 'Zľava (zaokrúhlené):',
	'rounding' => 'Zaokrúhlenie',
	'rounding_in_rate' => 'Zaokrúhlenie v sazbe ',
	'including_rounding' => 'Sumy sú vrátane hodnôt zaokrúhlenia',
	'paid_advances' => 'Zaplacené zálohy:',
	'already_paid_do_not_pay' => 'UŽ UHRADENÉ - NEPLATIŤ',

	// Footer Signature
	'stamp_and_signature' => 'Pečiatka, podpis dodávateľa',

	// Additional Info
	'additional_information' => 'Doplňujúce informácie:',

	// Tax Regime
	'reverse_charge_notice' => 'Faktúra je v režime prenesenia daňovej povinnosti podľa § 92e zákona o DPH, kedy výšku dane je povinný doplniť a priznať platiteľ, pre ktorého plnenie je uskutočnené.',

	// EET (Electronic Sales Registry)
	'electronic_sales_registry' => 'Elektronická evidencia tržieb:',
	'establishment' => 'Prevádzka',
	'cash_register' => 'Pokladňa',
	'fik_code' => 'FIK',
	'bkp_code' => 'BKP',
	'pkp_code' => 'PKP',
	'mode' => 'Režim',
];
