<?php declare(strict_types=1);

namespace Kenod\InvoiceGenerator;

use TCPDF;

/**
 * Main invoice PDF generator class
 *
 * This class generates professional PDF invoices with support for:
 * - Multiple document types (invoice, proforma, credit note, storno)
 * - VAT calculations with multiple rates
 * - QR payment codes
 * - Electronic signatures
 * - Multi-language support
 * - Custom styling and branding
 *
 * Extends TCPDF for PDF generation capabilities
 */
final class InvoiceGenerator extends TCPDF {
	protected Address $supplier;

	protected Address $customer;

	protected Address $endRecipient;

	protected Information $information;

	protected PaymentDetails $paymentDetails;

	protected Settings $settings;

	/** @var callable(self): void|null */
	protected $customCallback = null;

	/** @var list<InvoiceItem> */
	private array $items = [];

	private int $itemCount = 0;

	private float $totalPrice = 0;

	private float $yOffset = 0;

	private float $signatureY = 0;

	private float $totalDiscount = 0;

	private float $paymentDetailsY = 0;

	private int $invoiceNumber = 0;

	private int $invoicePageNo = 0;

	private bool $alreadyPaid = false;

	public function __construct() {
		parent::__construct();

		$this->settings = new Settings();
		$this->supplier = new Address();
		$this->customer = new Address();
		$this->endRecipient = new Address();
		$this->information = new Information();
		$this->paymentDetails = new PaymentDetails();

		// Set margins
		$this->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
		$this->SetHeaderMargin(PDF_MARGIN_HEADER);
		$this->SetFooterMargin(PDF_MARGIN_FOOTER);

		// Set auto page breaks
		$this->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

		// Set image scale factor
		$this->setImageScale(PDF_IMAGE_SCALE_RATIO);

		// Set default font subsetting mode
		$this->setFontSubsetting(true);

		// Set default font
		$this->SetFont($this->settings->getFont(), '', 14, '', true);

		$this->Open();

		// Set document creator
		$this->SetCreator('Generated by Kenod\InvoiceGenerator Library');

		// Set Y offset constant
		$this->yOffset = 5;
	}

	// phpcs:disable Generic.NamingConventions.CamelCapsFunctionName.ScopeNotCamelCaps

	/**
	 * TCPDF Footer override - renders page footer
	 */
	public function Footer(): void {
		$this->SetFont($this->settings->getFont(), '', 8);
		$this->SetDrawColor(180, 180, 180);
		$this->SetTextColor(180, 180, 180);
		$this->SetLineWidth(0.1);
		$this->Line(10, 287, 200, 287);
		$this->SetXY(15, -10);
		$this->Cell(0, 8, Translator::t('generated_footer'));
		$this->SetXY(0, -10);
		$this->Cell(210, 8, 'faktury.chci-www.cz', 0, 0, 'C');
		$this->SetXY(180, -10);
		$this->Cell(20, 8, Translator::t('page') . ' ' . $this->getPageNumGroupAlias() . '/' . $this->getPageGroupAlias(), 0, 0, 'L');
		$this->SetTextColor(0, 0, 0);
	}

	/**
	 * Main invoice generation method
	 *
	 * @param bool $output Whether to output PDF immediately
	 * @return mixed PDF output or true if $output is false
	 */
	public function generate(bool $output = true): mixed {
		$this->startPageGroup();
		$this->invoiceNumber++;

		// Load default language if none set
		if (!Translator::hasLanguage()) {
			$this->settings->setLanguage('cs');
		}

		// Translate all sections
		$this->supplier->translate();
		$this->customer->translate();
		$this->endRecipient->translate();
		$this->information->translate();
		$this->paymentDetails->translate();

		// Add discount item if configured
		$discount = $this->settings->getDiscount();

		if (
			(
				$discount[0] > 0
				|| $discount[3] === 1
			)
			&& (
				$discount[2] === 0
				|| $discount[2] === 2
			)
			&& $discount[1] === 0
		) {
			$this->items[] = new InvoiceItem(
				Translator::t('discount'),
				99,
				$discount[0],
				'',
				$discount[4],
				true,
			);
			$this->itemCount++;
		}

		// Add rounding item when rounding is enabled
		if ($this->settings->getRoundingEnabled() === 0 && $this->settings->getRoundTo() > 0) {
			$this->items[] = new InvoiceItem(Translator::t('rounding'), 1, 0, '', 0, true);
			$this->itemCount++;
		}

		// Set end recipient address if needed
		$finalRecipient = $this->settings->getFinalRecipient();
		if ($finalRecipient['display'] && !$finalRecipient['different_address']) {
			$this->endRecipient = $this->customer;
		}

		$this->AddPage();
		$this->invoicePageNo = $this->PageNo();

		// Electronic signature
		if ($this->settings->getSignatureCertificate() !== '') {
			$this->setSignature(
				$this->settings->getSignatureCertificate(),
				'',
				$this->settings->getSignaturePassword(),
				'',
				2,
				$this->settings->getSignatureInfo(),
			);
		}

		// Set author and title
		$this->SetAuthor($this->settings->getAuthor());
		$this->SetTitle($this->settings->getTitle());
		$this->SetAutoPageBreak(false, 0.5);

		// Render first page images
		foreach ($this->settings->getImages() as $image) {
			if ($image['repeat'] === 'F') {
				$this->Image(
					$image['path'],
					$image['x'],
					(float) $image['y'],
					$image['width'] ?? 0,
					$image['height'] ?? 0,
				);
			}
		}

		// Render supplier and customer sections
		$style = $this->settings->getStyle();
		$this->SetFillColor(
			$style['fillColor'][0],
			$style['fillColor'][1],
			$style['fillColor'][2],
		);
		$this->SetTextColor(
			$style['fontColor'][0],
			$style['fontColor'][1],
			$style['fontColor'][2],
		);
		$this->Rect(10, 20, 190, 10, 'F', $this->settings->getBorders());

		// Render barcode if configured
		$barcode = $this->settings->getBarcode();
		if ($barcode['code'] > 0) {
			$barcodeStyle = [
				'position' => '',
				'align' => 'C',
				'stretch' => false,
				'fitwidth' => true,
				'cellfitalign' => '',
				'border' => false,
				'hpadding' => 1,
				'vpadding' => 0,
				'fgcolor' => [0, 0, 0],
				'bgcolor' => false,
				'text' => false,
				'font' => $this->settings->getFont(),
				'fontsize' => 5.2,
				'stretchtext' => 0,
			];
			$this->write1DBarcode(
				(string) $barcode['code'],
				'c128',
				$barcode['left'],
				$barcode['top'],
				$barcode['width'],
				$barcode['height'],
				0.4,
				$barcodeStyle,
				'T',
			);
		}

		// Render supplier address
		$this->SetFont($this->settings->getFont(), 'B', 10);
		$this->SetXY(15, 20);
		$this->Cell(0, 10, Translator::t('supplier'));
		$this->SetTextColor(0, 0, 0);
		$this->renderAddress($this->supplier, 15, 33, 9, true);

		// Render customer address
		$this->SetTextColor(
			$style['fontColor'][0],
			$style['fontColor'][1],
			$style['fontColor'][2],
		);
		$this->SetFont($this->settings->getFont(), 'B', 10);
		$this->SetXY(113, 20);
		$this->Cell(0, 10, Translator::t('customer'));
		$this->SetTextColor(0, 0, 0);
		$this->renderAddress($this->customer, 113, 33, 9, true);

		// Render end recipient if configured
		if ($finalRecipient['display']) {
			$this->SetFillColor(
				$style['fillColor'][0],
				$style['fillColor'][1],
				$style['fillColor'][2],
			);
			$this->SetTextColor(
				$style['fontColor'][0],
				$style['fontColor'][1],
				$style['fontColor'][2],
			);
			$this->Rect(112, $this->getY() + 3, 87, 10, 'F', $this->settings->getBorders());
			$this->SetFont($this->settings->getFont(), 'B', 10);
			$this->SetXY(113, $this->getY() + 3);
			$this->Cell(0, 10, Translator::t('end_recipient'));
			$this->SetTextColor(0, 0, 0);
			$this->renderAddress($this->endRecipient, 113, $this->getY() + 13, 9, true);
		}

		$this->yOffset -= 62;

		// Render payment details section
		$this->SetFillColor(
			$style['fillColor'][0],
			$style['fillColor'][1],
			$style['fillColor'][2],
		);
		$this->Rect(10, $this->yOffset + 65, 190, 10, 'F', $this->settings->getBorders());

		$secondColumn = $this->renderInfoSection($this->paymentDetails, 15, 78 + $this->yOffset, 9, 37);
		$this->SetFont($this->settings->getFont(), 'B', 10);
		$this->SetXY(15, 65 + $this->yOffset);
		$this->SetTextColor(
			$style['fontColor'][0],
			$style['fontColor'][1],
			$style['fontColor'][2],
		);
		$this->Cell(0, 10, Translator::t('payment_details'));
		$this->SetTextColor(0, 0, 0);
		$firstColumn = $this->renderInfoSection($this->information, 113, 78 + $this->yOffset, 9, 50);

		$largerColumn = max($firstColumn, $secondColumn);
		$this->paymentDetailsY = $this->yOffset + 77;

		// Check if invoice is already paid
		$this->alreadyPaid = false;

		if ($this->settings->getDeposits() > 0) {
			if ($this->calculateTotal() - $this->settings->getDeposits() < 0.5) {
				$this->alreadyPaid = true;
			}
		}

		// Adjust for QR code space if needed
		$qrPayment = $this->settings->getQrPayment();
		if (
			$qrPayment['display'] &&
			$qrPayment['page'] === 'PU' &&
			!$this->alreadyPaid
		) {
			if ($largerColumn < $qrPayment['size'] + 6) {
				$largerColumn = $qrPayment['size'] + 6;
			}
		}

		$this->yOffset += $largerColumn;

		// Display "ALREADY PAID" message if applicable
		if ($this->settings->getAlreadyPaidInPaymentInfo() && $this->alreadyPaid) {
			$this->SetXY(15, $this->yOffset + 76);
			$this->SetFont($this->settings->getFont(), 'B', 20);
			$this->Cell(180, 10, Translator::t('already_paid_do_not_pay'), 0, 0, 'C');
			$this->yOffset += 15;
		}

		// Render items section
		$this->SetFillColor(
			$style['fillColor'][0],
			$style['fillColor'][1],
			$style['fillColor'][2],
		);
		$this->SetTextColor(
			$style['fontColor'][0],
			$style['fontColor'][1],
			$style['fontColor'][2],
		);
		$this->Rect(10, $this->yOffset + 76, 190, 10, 'F', $this->settings->getBorders());

		$this->SetFont($this->settings->getFont(), 'B', 10);
		$this->SetXY(15, 76 + $this->yOffset);
		$this->Cell(0, 10, Translator::t('items_to_pay'));
		$this->SetTextColor(0, 0, 0);

		$this->renderTableHeader(95);
		$this->renderItems();

		// Render footer text if configured
		$footerText = $this->settings->getFooterText();
		if ($footerText !== []) {
			$currentY = -16;

			foreach ($footerText as $footerTextItem) {
				if ($footerTextItem[0] !== '') {
					$this->SetXY(15, $currentY);
					$this->SetFont(
						$this->settings->getFont(),
						$footerTextItem[2],
						$footerTextItem[1],
					);
					$this->Cell(80, $footerTextItem[1] - 4, $footerTextItem[0], 0, 0, 'L');
					$currentY += $footerTextItem[1] - 4;
				}
			}
		}

		// Render last page images
		foreach ($this->settings->getImages() as $image) {
			if ($image['repeat'] === 'L') {
				$vertical = is_string($image['y']) && str_starts_with((string) $image['y'], 'c')
					? $this->calculateRelativePosition((string) $image['y'], $this->signatureY)
					: (float) $image['y'];
				$this->Image(
					$image['path'],
					$image['x'],
					$vertical,
					$image['width'] ?? 0,
					$image['height'] ?? 0,
				);
			}
		}

		// Render QR payment on last page if configured
		if (
			!$this->alreadyPaid
			&& $qrPayment['display']
			&& $qrPayment['page'] === 'L'
		) {
			$yPosition = $qrPayment['y'];
			$vertical = is_string($yPosition) && str_starts_with($yPosition, 'c')
				? $this->calculateRelativePosition($yPosition, $this->signatureY)
				: (float) $yPosition;
			$this->renderQRPayment($qrPayment['x'], $vertical);
		}

		$this->SetDisplayMode('real');

		// Render QR payment on first page if configured
		if (
			!$this->alreadyPaid &&
			$qrPayment['display'] &&
			($qrPayment['page'] === 'F' || $qrPayment['page'] === 'PU')
		) {
			$this->SetPage(1);
			$yPos = $qrPayment['page'] === 'PU'
				? $this->paymentDetailsY + 1
				: (float) $qrPayment['y'];
			$this->renderQRPayment($qrPayment['x'], $yPos);
		}

		// Execute custom callback if set
		if (is_callable($this->customCallback)) {
			($this->customCallback)($this);
		}

		return $output ? $this->outputPDF() : true;
	}

	/**
	 * Outputs generated PDF
	 *
	 * @return mixed PDF output
	 */
	public function outputPDF(): mixed {
		return $this->Output($this->settings->getFilename(), $this->settings->getOutputType());
	}

	/**
	 * Clears invoice data for generating next invoice
	 */
	public function clearData(): self {
		$this->customer = new Address();
		$this->endRecipient = new Address();
		$this->information = new Information();
		$this->paymentDetails = new PaymentDetails();
		$this->items = [];
		$this->itemCount = 0;
		$this->totalPrice = 0;
		$this->totalDiscount = 0;
		$this->alreadyPaid = false;
		$this->settings->clear();

		return $this;
	}

	/**
	 * Gets total invoice price (call after generation)
	 */
	public function getTotalPrice(): float {
		return $this->totalPrice;
	}

	public function getSupplier(): Address {
		return $this->supplier;
	}

	public function setSupplier(Address $supplier): self {
		$this->supplier = $supplier;

		return $this;
	}

	public function getCustomer(): Address {
		return $this->customer;
	}

	public function setCustomer(Address $customer): self {
		$this->customer = $customer;

		return $this;
	}

	public function getEndRecipient(): Address {
		return $this->endRecipient;
	}

	public function setEndRecipient(Address $endRecipient): self {
		$this->endRecipient = $endRecipient;

		return $this;
	}

	public function getInformation(): Information {
		return $this->information;
	}

	public function setInformation(Information $information): self {
		$this->information = $information;

		return $this;
	}

	public function getPaymentDetails(): PaymentDetails {
		return $this->paymentDetails;
	}

	public function setPaymentDetails(PaymentDetails $paymentDetails): self {
		$this->paymentDetails = $paymentDetails;

		return $this;
	}

	public function getSettings(): Settings {
		return $this->settings;
	}

	public function setSettings(Settings $settings): self {
		$this->settings = $settings;

		return $this;
	}

	/**
	 * @return callable(self): void|null
	 */
	public function getCustomCallback(): ?callable {
		return $this->customCallback;
	}

	/**
	 * @param callable(self): void|null $customCallback
	 */
	public function setCustomCallback(?callable $customCallback): self {
		$this->customCallback = $customCallback;

		return $this;
	}

	/**
	 * Calculate and return final prices including VAT breakdown
	 *
	 * For non-VAT payers returns: ['total' => float]
	 * For VAT payers returns: ['total' => float, 'vat_summary' => ['rate' => ['base' => float, 'vat' => float, 'total' => float]]]
	 *
	 * @return array<string, mixed> Price breakdown
	 */
	public function getFinalPrices(): array {
		$vatSummary = [];
		$baseByRate = [];
		$vatByRate = [];
		$totalPrice = 0;

		// Calculate prices from items
		foreach ($this->items as $item) {
			if ($this->settings->getVatPayer()) {
				// VAT payer calculation
				$basePrice = $item->getPrice();
				if ($this->settings->getAmountsWithVat()) {
					$basePrice = $item->getPrice() / (1 + $item->getVat() / 100);
				}

				$itemBase = $basePrice * $item->getQuantity();
				$vatAmount = $itemBase * $item->getVat() / 100;

				// Initialize rate arrays if not exists
				$rateKey = (string) $item->getVat();
				if (!isset($baseByRate[$rateKey])) {
					$baseByRate[$rateKey] = 0;
					$vatByRate[$rateKey] = 0;
				}

				if (!$this->settings->getReverseCharge()) {
					$vatByRate[$rateKey] += $vatAmount;
				}

				$baseByRate[$rateKey] += $itemBase;
				$totalPrice += $itemBase + $vatAmount;
			} else {
				// Non-VAT payer calculation
				$totalPrice += $item->getPrice() * $item->getQuantity();
			}
		}

		// Apply discount if set
		$discount = $this->settings->getDiscount();
		if ($discount[0] > 0) {
			if ($discount[1] == 1) {
				// Percentage discount
				$totalPrice *= (1 - $discount[0] / 100);
			} else {
				// Fixed amount discount
				$totalPrice -= $discount[0];
			}
		}

		// Apply rounding if set and not disabled
		if ($this->settings->getRoundTo() > 0 && $this->settings->getRoundingEnabled() !== 2) {
			switch ($this->settings->getRoundingMethod()) {
				case 2: // Round up
					$totalPrice = ceil($totalPrice / $this->settings->getRoundTo()) * $this->settings->getRoundTo();

					break;
				case 3: // Round down
					$totalPrice = floor($totalPrice / $this->settings->getRoundTo()) * $this->settings->getRoundTo();

					break;
				default: // Mathematical rounding
					$totalPrice = round($totalPrice / $this->settings->getRoundTo()) * $this->settings->getRoundTo();

					break;
			}
		}

		// Subtract advances/deposits
		$totalPrice -= $this->settings->getDeposits();

		// Build VAT summary for VAT payers
		if ($this->settings->getVatPayer()) {
			foreach ($baseByRate as $rate => $base) {
				$vatSummary[$rate] = [
					'base' => round($base, 2),
					'vat' => round($vatByRate[$rate] ?? 0, 2),
					'total' => round($base + ($vatByRate[$rate] ?? 0), 2),
				];
			}

			return [
				'total' => round($totalPrice, 2),
				'vat_summary' => $vatSummary,
			];
		}

		return ['total' => round($totalPrice, 2)];
	}

	/**
	 * Adds invoice line item
	 *
	 * @param string $name Item name/description
	 * @param float $quantity Quantity
	 * @param float $price Unit price
	 * @param string $unit Unit of measurement
	 * @param float $vat VAT rate (e.g., 21 for 21%)
	 * @param string $note Additional note
	 * @param int|null $ean EAN barcode
	 * @return bool Success status
	 */
	public function addItem(
		string $name,
		float $quantity = 1,
		float $price = 0,
		string $unit = '',
		float $vat = 0,
		string $note = '',
		?int $ean = null,
	): bool {
		$this->items[] = new InvoiceItem($name, $quantity, $price, $unit, $vat, false, $ean, $note);
		$this->itemCount++;

		return true;
	}

	/**
	 * Draws a dashed horizontal line
	 */
	private function dashedLine(float $x1, float $y1, float $x2, float $segments = 15): void {
		$dashLength = abs($x1 - $x2) / $segments / 2;

		for ($i = $x1; $i < $x2; $i += $dashLength * 2) {
			$this->Line($i, $y1, $i + $dashLength, $y1);
		}
	}

	/**
	 * TCPDF Header callback - renders document title and number on each page
	 *
	 * phpcs:disable Generic.NamingConventions.CamelCapsFunctionName.ScopeNotCamelCaps
	 */
	public function Header(): void {
		$this->SetDrawColor(0, 0, 0);
		$this->SetFont($this->settings->getFont(), '', 12);
		$this->SetXY(10, 10);

		// Render document name or default title based on document type
		if (!empty($this->settings->getDocumentName())) {
			$this->Cell(187, 10, $this->settings->getDocumentName(), '', 0, 'R');
		} else {
			switch ($this->settings->getDocumentType()) {
				case 1:
					// Regular invoice
					if ($this->settings->getVatPayer()) {
						$this->Cell(187, 10, Translator::t('invoice_header_taxpayer') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					} else {
						$this->Cell(187, 10, Translator::t('invoice_header_non_taxpayer') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					}

					break;
				case 2:
					// Proforma
					$this->Cell(187, 10, Translator::t('proforma_invoice_header') . $this->settings->getInvoiceNumber(), '', 0, 'R');

					break;
				case 3:
					// Credit note / correction
					if ($this->settings->getVatPayer()) {
						$this->Cell(187, 10, Translator::t('corrective_document_header') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					} else {
						$this->Cell(187, 10, Translator::t('credit_note_header') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					}

					break;
				case 4:
					// Cancellation
					if ($this->settings->getVatPayer()) {
						$this->Cell(187, 10, Translator::t('cancelled_invoice_header_taxpayer') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					} else {
						$this->Cell(187, 10, Translator::t('cancelled_invoice_header') . $this->settings->getInvoiceNumber(), '', 0, 'R');
					}

					break;
			}
		}

		// Render images that should appear on all pages (type 'A')
		$images = $this->settings->getImages();
		if (count($images) > 0) {
			foreach ($images as $image) {
				if (trim($image['path']) !== '' && $image['repeat'] === 'A') {
					$this->Image(
						$image['path'],
						$image['x'],
						is_string($image['y']) ? (float) $image['y'] : $image['y'],
						$image['width'] ?? 0,
						$image['height'] ?? 0,
					);
				}
			}
		}
	}

	/**
	 * Renders items table header
	 *
	 * @param float $indent Y position for header (without yOffset applied)
	 * @return int Return value for offset adjustment
	 */
	private function renderTableHeader(float $indent): int {
		$return = 0;

		// Check if we're on a new page and need to render "Items to pay" header
		if ($this->invoicePageNo !== $this->PageNo()) {
			$style = $this->settings->getStyle();
			$this->SetFillColor(
				$style['fillColor'][0],
				$style['fillColor'][1],
				$style['fillColor'][2],
			);
			$this->SetTextColor(
				$style['fontColor'][0],
				$style['fontColor'][1],
				$style['fontColor'][2],
			);
			$this->Rect(10, $this->yOffset + $indent - 10, 190, 10, 'F', $this->settings->getBorders());

			$this->SetFont($this->settings->getFont(), 'B', 10);
			$this->SetXY(15, $indent - 10 + $this->yOffset);
			$this->Cell(0, 10, Translator::t('items_to_pay'));
			$this->SetTextColor(0, 0, 0);
			$return = 9;
			$indent += 9;
		}

		if ($this->settings->getVatPayer()) {
			// VAT payer header
			$this->SetFont($this->settings->getFont(), 'B', 7);
			$this->SetXY(15, $indent - 9 + $this->yOffset);
			$this->Cell(0, 10, Translator::t('item_name'));

			if ($this->settings->getDisplayedColumnsCount() > 0) {
				$this->SetX(70 + 35 - $this->settings->getDisplayedColumnsWidth());
				$columnOffset = 0;

				$displayedColumns = $this->settings->getDisplayedColumns();
				if ($displayedColumns['pocetmj']) {
					$this->Cell(17, 10, Translator::t('quantity'), 0, 0, 'R');
					$columnOffset += 17;
				}

				if ($displayedColumns['mj']) {
					$this->SetX(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset);
					$this->Cell(8, 10, Translator::t('unit'), 0, 0, 'L');
					$columnOffset += 8;
				}

				if ($displayedColumns['cenamj']) {
					$this->SetX(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset);
					$this->Cell(18, 10, Translator::t('unit_price'), 0, 0, 'R');
				}
			}

			$this->SetX(114);
			$this->Cell(11, 10, Translator::t('vat_rate'), 0, 0, 'R');
			$this->SetX(126);
			$this->Cell(23, 10, Translator::t('excl_vat'), 0, 0, 'R');
			$this->SetX(152);
			$this->Cell(19, 10, Translator::t('vat'), 0, 0, 'R');
			$this->SetX(172);
			$this->Cell(23, 10, Translator::t('incl_vat'), 0, 0, 'R');
		} else {
			// Non-VAT payer header
			$this->SetFont($this->settings->getFont(), 'B', 9);
			$this->SetXY(15, $indent - 9 + $this->yOffset);
			$this->Cell(0, 10, Translator::t('item_name'));

			if ($this->settings->getDisplayedColumnsCount() > 0) {
				$this->SetX(95 + 65 - $this->settings->getDisplayedColumnsWidth(false));
				$columnOffset = 0;

				$displayedColumns = $this->settings->getDisplayedColumns();
				if ($displayedColumns['pocetmj']) {
					$this->Cell(20, 10, Translator::t('quantity'), 0, 0, 'R');
					$columnOffset += 25;
				}

				if ($displayedColumns['mj']) {
					$this->SetX(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset);
					$this->Cell(15, 10, Translator::t('unit'));
					$columnOffset += 15;
				}

				if ($displayedColumns['cenamj']) {
					$this->SetX(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset);
					$this->Cell(25, 10, Translator::t('unit_price'), 0, 0, 'R');
				}
			}

			$this->SetX(170);
			$this->Cell(25, 10, Translator::t('total_price'), 0, 0, 'R');
		}

		// Draw gray separator line
		$this->SetDrawColor(153, 153, 153);
		$this->Line(15, $indent + $this->yOffset, 195, $indent + $this->yOffset);
		$this->SetDrawColor(0, 0, 0);
		$this->SetFont($this->settings->getFont(), '', 9);

		return $return;
	}

	/**
	 * Calculates position relative to signature line
	 */
	private function calculateRelativePosition(string $position, float $signatureY): float {
		if (str_contains($position, '+')) {
			return $signatureY + (float) substr($position, strpos($position, '+') + 1);
		}

		return $signatureY - (float) substr($position, strpos($position, '-') + 1);
	}

	/**
	 * Calculates total price with VAT, discounts, and rounding
	 *
	 * @return float Total price
	 */
	private function calculateTotal(): float {
		$total = 0;
		$discount = 0;

		foreach ($this->items as $item) {
			if ($item->getSpecial()) {
				// Handle special items (discount/rounding)
				if ($item->getQuantity() === 99.0) {
					// Discount item
					$discount = -$item->getPrice();
					$total += $discount;
				} else {
					// Rounding item - calculate rounding
					$rounded = match ($this->settings->getRoundingMethod()) {
						2 => ceil($this->settings->getRoundTo() * $total) / $this->settings->getRoundTo(),
						3 => floor($this->settings->getRoundTo() * $total) / $this->settings->getRoundTo(),
						default => round($this->settings->getRoundTo() * $total, $this->settings->getRoundingEnabled()) / $this->settings->getRoundTo(),
					};
					$total = $rounded;
				}
			} else {
				// Normal item
				$itemTotal = $item->getQuantity() * $item->getPrice();
				$total += $item->getVat() > 0 ? $itemTotal * (1 + $item->getVat() / 100) : $itemTotal;
			}
		}

		return $total;
	}

	/**
	 * Renders all invoice items with pagination support
	 *
	 * This is the most complex method - handles item rendering, page breaks,
	 * VAT calculations, totals, and footer rendering
	 */
	private function renderItems(): void {
		// Initialize VAT arrays for VAT payers
		$vatBaseTotal = [];
		$vatTotal = [];

		if ($this->settings->getVatPayer()) {
			$this->SetFont($this->settings->getFont(), '', 8);

			foreach ($this->settings->getVatRates() as $rate => $label) {
				$vatBaseTotal[$rate] = 0;
				$vatTotal[$rate] = 0;
			}
		} else {
			$this->SetFont($this->settings->getFont(), '', 9);
		}

		$y = 96 + $this->yOffset;
		$this->SetXY(15, $y);
		$this->SetFillColor(204, 204, 204);
		$itemIndex = 1;

		// Calculate footer height for pagination
		$this->startTransaction();
		$footerYTest = $this->getY();
		$this->renderFooter();
		$footerHeight = $this->getY() - $footerYTest;
		$this->rollbackTransaction(true);

		// Calculate page break constants
		$pageBreakAdjustment = 0;

		// Check if discount should be displayed
		$showDiscount = false;

		$discount = $this->settings->getDiscount();
		if (($discount[0] > 0 || $discount[3] === 1) && $discount[1] === 1) {
			$showDiscount = true;
		}

		if (
			(
				$discount[0] > 0
				|| $discount[3] === 1
			)
			&& $discount[1] === 0
			&& $discount[2] > 0
		) {
			$showDiscount = true;
		}

		if ($this->settings->getVatPayer() && $this->settings->getVatSummary()) {
			$pageBreakAdjustment -= 7;
		} else {
			if (!$showDiscount) {
				$pageBreakAdjustment += 7;
			}
		}

		$pageBreakItems = 297 - 15 - 40 - $footerHeight + $pageBreakAdjustment;
		$pageBreakEnd = 297 - 15;
		$itemNumber = 0;

		// Style for EAN barcodes
		$barcodeStyle = [
			'position' => '',
			'align' => 'C',
			'stretch' => false,
			'fitwidth' => true,
			'cellfitalign' => '',
			'border' => false,
			'hpadding' => 1,
			'vpadding' => 4,
			'fgcolor' => [0, 0, 0],
			'bgcolor' => false,
			'text' => true,
			'font' => $this->settings->getFont(),
			'fontsize' => 5.2,
			'stretchtext' => 0,
		];

		$yExtra = 0;
		$isRounded = false;

		// Loop through all items
		foreach ($this->items as $item) {
			$itemNumber++;
			$pageBreakPoint = $itemNumber + 1 >= $this->itemCount ? $pageBreakItems : $pageBreakEnd;

			$this->setCellPaddings(0, 0.75, 0, 0.75);

			// Check if page break needed
			if (
				$this->GetY() > $pageBreakPoint
				|| ($this->getStringHeight(55, $item->getName()) + $y) >= $pageBreakPoint
			) {
				$this->AddPage();
				$this->yOffset = 0;
				$headerReturn = $this->renderTableHeader(30);
				$y = 32 + $headerReturn;

				if ($this->settings->getVatPayer()) {
					$this->SetFont($this->settings->getFont(), '', 8);
				} else {
					$this->SetFont($this->settings->getFont(), '', 9);
				}
			}

			// Alternating row colors
			$fillRow = false;

			if ($itemIndex % 2 === 0) {
				$style = $this->settings->getStyle();
				if (is_array($style['itemFillColor'])) {
					$this->SetFillColor(
						$style['itemFillColor'][0],
						$style['itemFillColor'][1],
						$style['itemFillColor'][2],
					);
					$this->SetTextColor(
						$style['itemFontColor'][0] ?? 0,
						$style['itemFontColor'][1] ?? 0,
						$style['itemFontColor'][2] ?? 0,
					);
					$fillRow = true;
				} else {
					$this->SetFillColor(255, 255, 255);
					$this->SetTextColor(0, 0, 0);
				}
			} else {
				$this->SetFillColor(255, 255, 255);
				$this->SetTextColor(0, 0, 0);
			}

			// Apply percentage discount to each item if configured
			if ($discount[0] > 0 && $discount[1] === 1) {
				$item->setPrice($item->getPrice() * (100 - $discount[0]) / 100);
			}

			if ($this->settings->getVatPayer()) {
				// VAT payer rendering
				$this->renderItemVatPayer(
					$item,
					$y,
					$yExtra,
					$fillRow,
					$barcodeStyle,
					$vatBaseTotal,
					$vatTotal,
					$isRounded,
					$itemNumber,
				);
			} else {
				// Non-VAT payer rendering
				$this->renderItemNonVatPayer(
					$item,
					$y,
					$yExtra,
					$fillRow,
					$barcodeStyle,
					$itemNumber,
				);
			}

			$itemIndex++;
		}

		$this->SetTextColor(0, 0, 0);

		// Calculate final Y position for totals
		$totalAreaAdjustment = $this->totalPrice - $this->settings->getDeposits() > 0.5 ? 213 : 202;

		if ($this->settings->getVatPayer() && $this->settings->getVatSummary()) {
			$totalAreaAdjustment -= 27;
		}

		$this->SetXY(15, $y + 5);
		$yLastItem = $this->getY();
		$this->SetFont($this->settings->getFont(), 'B', 9);
		$this->SetLineWidth(0.5);
		$this->Line(10.2, $y + 2, 199.8, $y + 2);
		$this->SetLineWidth(0.2);

		$xOffset = 5;

		// Render VAT summary for VAT payers
		if ($this->settings->getVatPayer() && $this->settings->getVatSummary()) {
			$xOffset = 0;
			$this->renderVatSummary($y, $vatBaseTotal, $vatTotal, $isRounded);
		}

		$ySignature = $this->getY();
		$this->renderTotals($yLastItem, $xOffset, $showDiscount);

		if ($this->getY() > $ySignature) {
			$ySignature = $this->getY();
		}

		$this->signatureY = $ySignature;
		$this->renderFooter($ySignature);
	}

	/**
	 * Renders a single item for VAT payer
	 *
	 * @param array<string, mixed> $barcodeStyle Barcode rendering style
	 * @param array<int|string, float> $vatBaseTotal VAT base totals by rate
	 * @param array<int|string, float> $vatTotal VAT totals by rate
	 * @param-out float|int $yExtra
	 */
	private function renderItemVatPayer(
		InvoiceItem $item,
		float &$y,
		float &$yExtra,
		bool $fillRow,
		array $barcodeStyle,
		array &$vatBaseTotal,
		array &$vatTotal,
		bool &$isRounded,
		int $itemNumber,
	): void {
		$y += 0.25 + $yExtra;
		$this->SetXY(15, $y);

		$noteWidth = 100;

		if ($this->settings->getDisplayedColumnsCount() > 0) {
			$noteWidth -= $this->settings->getDisplayedColumnsWidth() + 5;
		}

		$hasEan = false;
		$eanY = 0;

		// Test render to calculate heights
		$this->startTransaction();
		$yExtra = 0;
		$y1 = $y;

		// Render EAN barcode if present
		if ($item->getEan() !== null && $item->getEan() > 0) {
			$hasEan = true;
			$this->write1DBarcode((string) $item->getEan(), 'c128', null, null, 30, 8, 0.4, $barcodeStyle, 'T');
			$noteWidth -= $this->getX() - 15;
			$eanY = $this->getY();
		}

		$x2 = $this->getX();
		$this->SetXY($x2, $y);

		// Render note above name if configured
		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'top') {
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 8);
			$this->setXY($x2, $this->GetY());
		}

		$this->MultiCell($noteWidth, 5, $item->getName(), 0, 'L', false, 1, null, null, true, 0, false, true, 0, 'B');

		// Render note below name if configured
		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'bottom') {
			$this->setXY($x2, $this->GetY());
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 8);
		}

		$y2 = $this->GetY();

		if ($y1 + 8 > $y2 && $hasEan) {
			$yExtra = 0.0;
			$y2 += 3;
		}

		$this->rollbackTransaction(true);

		$rowHeight = $y2 - $y1 + $yExtra;
		$this->setCellPaddings(0, 0, 0, 0);

		// Fill row background if needed
		if ($fillRow) {
			$this->Rect(14, $y1 - 0.15, 182, $rowHeight - 0.15 + $yExtra, 'F');
		}

		// Actual render - repeat the rendering logic
		if ($item->getEan() !== null && $item->getEan() > 0) {
			$this->write1DBarcode((string) $item->getEan(), 'c128', null, null, 30, 8, 0.4, $barcodeStyle, 'T');
		}

		$x2 = $this->getX();
		$this->SetXY($x2, $y);

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'top') {
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 8);
			$this->setXY($x2, $this->GetY());
		}

		$this->MultiCell($noteWidth, 5, $item->getName(), 0, 'L', false, 1, null, null, true, 0, false, true, 0, 'B');

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'bottom') {
			$this->setXY($x2, $this->GetY());
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 8);
		}

		// Draw underline if configured
		$underline = $this->settings->getUnderline();
		if (is_array($underline) && $this->itemCount > $itemNumber) {
			$this->SetDrawColor(
				(int) ($underline[0] ?? 0),
				(int) ($underline[1] ?? 0),
				(int) ($underline[2] ?? 0),
			);
			$this->SetLineWidth(0.2);
			$this->Line(15, $y2 + $yExtra, 195, $y2 + $yExtra);
			$this->SetDrawColor(0, 0, 0);
		}

		// Handle special items (discount/rounding)
		if ($item->getSpecial()) {
			if ($item->getQuantity() === 99.0) {
				// Discount item
				$this->totalDiscount = -$item->getPrice();
				$this->totalPrice += $this->totalDiscount;
				$vatBaseTotal[(string) $item->getVat()] += $this->totalDiscount;

				$this->SetXY(126, $y);
				$this->Cell(23, 5, number_format($this->totalDiscount, 2, ',', ' '), 0, 0, 'R');
				$this->SetXY(152, $y);
				$this->Cell(19, 5, number_format(0, 2, ',', ' '), 0, 0, 'R');
				$this->SetXY(172, $y);
				$this->Cell(23, 5, number_format($this->totalDiscount, 2, ',', ' '), 0, 0, 'R');
			} else {
				// Rounding item
				$rounded = match ($this->settings->getRoundingMethod()) {
					2 => ceil($this->settings->getRoundTo() * $this->totalPrice) / $this->settings->getRoundTo(),
					3 => floor($this->settings->getRoundTo() * $this->totalPrice) / $this->settings->getRoundTo(),
					default => round($this->settings->getRoundTo() * $this->totalPrice, $this->settings->getRoundingEnabled()) / $this->settings->getRoundTo(),
				};

				$roundingDiff = $rounded - $this->totalPrice;
				$this->totalPrice += $roundingDiff;

				// Find which VAT rate to apply rounding to
				$usedRates = [];
				$maxRate = 0;
				$maxRateSum = 0;

				foreach ($vatBaseTotal as $rate => $amount) {
					if ($amount !== 0.0) {
						$usedRates[] = (float) $rate;
					}

					if ($amount > $maxRateSum) {
						$maxRate = (float) $rate;
						$maxRateSum = $amount;
					}
				}

				$roundingRate = match ($this->settings->getRoundingDistribution()) {
					1 => $usedRates !== [] ? max($usedRates) : 0,
					2 => $usedRates !== [] ? min($usedRates) : 0,
					3 => $maxRate,
					default => 0,
				};

				$roundingBase = 100 / (100 + $roundingRate) * $roundingDiff;

				$roundingVat = $this->settings->getRoundingType() === 1
					? $roundingDiff - $roundingBase
					: $roundingDiff - round($roundingBase, 2);

				if (!$this->settings->getReverseCharge()) {
					$vatTotal[(string) $roundingRate] += round($roundingVat, 2);
					$vatBaseTotal[(string) $roundingRate] += round($roundingBase, 2);
				} else {
					$roundingVat = 0;
					$roundingBase = $roundingDiff;
					$vatBaseTotal[(string) $roundingRate] += round($roundingDiff, 2);
				}

				// Render rounding columns
				if ($this->settings->getDisplayedColumnsCount() > 0) {
					$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth(), $y);
					$columnOffset = 0;

					$displayedColumns = $this->settings->getDisplayedColumns();
					if ($displayedColumns['pocetmj']) {
						$this->Cell(17, 5, '1', 0, 0, 'R');
						$columnOffset += 17;
					}

					if ($displayedColumns['mj']) {
						$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset, $y);
						$this->Cell(0, 5, '');
						$columnOffset += 9;
					}

					if ($displayedColumns['cenamj']) {
						$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset, $y);
						$this->Cell(18, 5, number_format($roundingBase, 2, ',', ' '), 0, 0, 'R');
					}
				}

				$this->SetXY(114, $y);
				$this->Cell(11, 5, (string) $roundingRate, 0, 0, 'R');
				$this->SetXY(126, $y);
				$this->Cell(23, 5, number_format($roundingBase, 2, ',', ' '), 0, 0, 'R');
				$this->SetXY(152, $y);
				$this->Cell(19, 5, number_format($roundingVat, 2, ',', ' '), 0, 0, 'R');
				$this->SetXY(172, $y);
				$this->Cell(23, 5, number_format(round($roundingDiff, 2) === 0.0 ? 0 : $roundingDiff, 2, ',', ' '), 0, 0, 'R');

				$isRounded = true;

				if ($this->settings->getRoundingAsItem()) {
					$this->itemCount--;
				}
			}
		} else {
			// Normal item
			$priceBase = $item->getPrice();

			if ($this->settings->getAmountsWithVat()) {
				$priceBase = $item->getPrice() - ($item->getPrice() * round(1 - (100 / (100 + $item->getVat())), 4));
			}

			// Render displayed columns
			if ($this->settings->getDisplayedColumnsCount() > 0) {
				$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth(), $y);
				$columnOffset = 0;

				$displayedColumns = $this->settings->getDisplayedColumns();
				if ($displayedColumns['pocetmj']) {
					$this->Cell(17, 5, (string) $item->getQuantity(), 0, 0, 'R');
					$columnOffset += 17;
				}

				if ($displayedColumns['mj']) {
					$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset, $y);
					$this->Cell(0, 5, $item->getUnit());
					$columnOffset += 9;
				}

				if ($displayedColumns['cenamj']) {
					$this->SetXY(70 + 35 - $this->settings->getDisplayedColumnsWidth() + $columnOffset, $y);
					$this->Cell(18, 5, number_format($priceBase, 2, ',', ' '), 0, 0, 'R');
				}
			}

			$this->SetXY(114, $y);
			$this->Cell(11, 5, (string) $item->getVat(), 0, 0, 'R');
			$this->SetXY(126, $y);
			$this->Cell(23, 5, number_format($priceBase * $item->getQuantity(), 2, ',', ' '), 0, 0, 'R');
			$this->SetXY(152, $y);

			$vatAmount = !$this->settings->getReverseCharge()
				? ($this->settings->getAmountsWithVat()
					? $item->getQuantity() * $item->getPrice() * round(1 - (100 / (100 + $item->getVat())), 4)
					: $item->getPrice() * $item->getQuantity() * $item->getVat() / 100)
				: 0;

			$totalWithVat = $priceBase * $item->getQuantity() + $vatAmount;

			$this->Cell(19, 5, number_format($vatAmount, 2, ',', ' '), 0, 0, 'R');
			$this->SetXY(172, $y);
			$this->Cell(23, 5, number_format($totalWithVat, 2, ',', ' '), 0, 0, 'R');

			// Update totals
			if ($this->settings->getRoundingType() === 1) {
				$vatTotal[(string) $item->getVat()] += $vatAmount;
				$vatBaseTotal[(string) $item->getVat()] += $priceBase * $item->getQuantity();
			} else {
				$vatTotal[(string) $item->getVat()] += round($vatAmount, 2);
				$vatBaseTotal[(string) $item->getVat()] += round($priceBase * $item->getQuantity(), 2);
			}

			$this->SetX(15);

			if ($this->settings->getRoundingType() === 1) {
				$this->totalPrice += $totalWithVat;
			} else {
				$this->totalPrice += round($totalWithVat, 2);
			}
		}

		$y = $y2 + $this->settings->getItemSpacing();
	}

	/**
	 * Renders a single item for non-VAT payer
	 *
	 * @param array<string, mixed> $barcodeStyle Barcode rendering style
	 * @param-out int $yExtra
	 */
	private function renderItemNonVatPayer(
		InvoiceItem $item,
		float &$y,
		float &$yExtra,
		bool $fillRow,
		array $barcodeStyle,
		int $itemNumber,
	): void {
		$y += 0.25 + $yExtra;
		$this->SetXY(15, $y);

		$noteWidth = 155;

		if ($this->settings->getDisplayedColumnsCount() > 0) {
			$noteWidth -= $this->settings->getDisplayedColumnsWidth(false) + 5;
		}

		$hasEan = false;

		// Test render to calculate heights
		$y1 = $y;
		$this->startTransaction();
		$yExtra = 0;
		$y2 = $y;

		if ($item->getEan() !== null && $item->getEan() > 0) {
			$hasEan = true;
			$this->write1DBarcode((string) $item->getEan(), 'c128', null, null, 30, 8, 0.4, $barcodeStyle, 'T');
			$yExtra = 1;
			$y2 = $this->getY() + 1;
			$noteWidth -= $this->getX() - 15;
		}

		$x2 = $this->getX();
		$this->SetXY($x2, $y);

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'top') {
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 9);
			$this->setXY($x2, $this->GetY());

			if ($hasEan) {
				$yExtra = 0;
				--$y2;
			}
		}

		$this->MultiCell($noteWidth, 5, $item->getName(), 0, 'L', false, 1, null, null, true, 0, false, true, 0, 'B');

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'bottom') {
			$this->setXY($x2, $this->GetY());
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 9);

			if ($hasEan) {
				$yExtra = 0;
				--$y2;
			}
		}

		$y2 = $this->GetY();
		$this->rollbackTransaction(true);

		$rowHeight = $y2 - $y1 + $yExtra;
		$this->setCellPaddings(0, 0, 0, 0);

		if ($fillRow) {
			$this->Rect(15, $y1 - 0.1, 180, $rowHeight - 0.1 + $yExtra, 'F');
		}

		// Actual render
		if ($item->getEan() !== null && $item->getEan() > 0) {
			$this->write1DBarcode((string) $item->getEan(), 'c128', null, null, 30, 8, 0.4, $barcodeStyle, 'T');
			++$y2;
		}

		$x2 = $this->getX();
		$this->SetXY($x2, $y);

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'top') {
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 9);
			$this->setXY($x2, $this->GetY());

			if ($hasEan) {
				--$y2;
			}
		}

		$this->MultiCell($noteWidth, 5, $item->getName(), 0, 'L', false, 1, null, null, true, 0, false, true, 0, 'B');

		if (!empty($item->getNote()) && $this->settings->getNotePosition() === 'bottom') {
			$this->setXY($x2, $this->GetY());
			$this->SetFont($this->settings->getFont(), '', 6);
			$this->MultiCell($noteWidth, 3, $item->getNote(), 0, 'L', false);
			$this->SetFont($this->settings->getFont(), '', 9);

			if ($hasEan) {
				--$y2;
			}
		}

		// Draw underline if configured
		$underline = $this->settings->getUnderline();
		if (is_array($underline) && $this->itemCount > $itemNumber) {
			$this->SetDrawColor(
				(int) ($underline[0] ?? 0),
				(int) ($underline[1] ?? 0),
				(int) ($underline[2] ?? 0),
			);
			$this->SetLineWidth(0.2);
			$this->Line(15, $y2 + $yExtra, 195, $y2 + $yExtra);
			$this->SetDrawColor(0, 0, 0);
		}

		// Handle special items
		if ($item->getSpecial()) {
			if ($item->getQuantity() === 99.0) {
				// Discount
				$this->totalDiscount = -$item->getPrice();

				if ($this->settings->getRoundingType() === 1) {
					$this->totalPrice += $this->totalDiscount;
				} else {
					$this->totalPrice += round($this->totalDiscount, 2);
				}

				if ($this->settings->getDisplayedColumnsCount() > 0) {
					$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false), $y);
					$columnOffset = 0;

					$displayedColumns = $this->settings->getDisplayedColumns();
					if ($displayedColumns['pocetmj']) {
						$this->Cell(20, 5, '1', 0, 0, 'R');
						$columnOffset += 25;
					}

					if ($displayedColumns['mj']) {
						$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
						$this->Cell(0, 5, '');
						$columnOffset += 15;
					}

					if ($displayedColumns['cenamj']) {
						$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
						$this->Cell(25, 5, number_format($this->totalDiscount, 2, ',', ' '), 0, 0, 'R');
					}
				}

				$this->SetXY(170, $y);
				$this->Cell(25, 5, number_format($this->totalDiscount, 2, ',', ' '), 0, 0, 'R');
			} else {
				// Rounding
				$rounded = match ($this->settings->getRoundingMethod()) {
					2 => ceil($this->settings->getRoundTo() * $this->totalPrice) / $this->settings->getRoundTo(),
					3 => floor($this->settings->getRoundTo() * $this->totalPrice) / $this->settings->getRoundTo(),
					default => round($this->settings->getRoundTo() * $this->totalPrice, $this->settings->getRoundingEnabled()) / $this->settings->getRoundTo(),
				};

				$roundingDiff = $rounded - $this->totalPrice;

				if ($this->settings->getDisplayedColumnsCount() > 0) {
					$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false), $y);
					$columnOffset = 0;

					$displayedColumns = $this->settings->getDisplayedColumns();
					if ($displayedColumns['pocetmj']) {
						$this->Cell(20, 5, '', 0, 0, 'R');
						$columnOffset += 25;
					}

					if ($displayedColumns['mj']) {
						$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
						$this->Cell(0, 5, '');
						$columnOffset += 15;
					}

					if ($displayedColumns['cenamj']) {
						$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
						$this->Cell(25, 5, number_format($roundingDiff, 2, ',', ' '), 0, 0, 'R');
					}
				}

				$this->SetXY(170, $y);
				$this->Cell(25, 5, number_format($roundingDiff, 2, ',', ' '), 0, 0, 'R');
				$this->totalPrice += $roundingDiff;
			}
		} else {
			// Normal item
			if ($this->settings->getDisplayedColumnsCount() > 0) {
				$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false), $y);
				$columnOffset = 0;

				$displayedColumns = $this->settings->getDisplayedColumns();
				if ($displayedColumns['pocetmj']) {
					$this->Cell(20, 5, (string) $item->getQuantity(), 0, 0, 'R');
					$columnOffset += 25;
				}

				if ($displayedColumns['mj']) {
					$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
					$this->Cell(0, 5, $item->getUnit());
					$columnOffset += 15;
				}

				if ($displayedColumns['cenamj']) {
					$this->SetXY(95 + 65 - $this->settings->getDisplayedColumnsWidth(false) + $columnOffset, $y);
					$this->Cell(25, 5, number_format($item->getPrice(), 2, ',', ' '), 0, 0, 'R');
				}
			}

			$this->SetXY(170, $y);
			$this->Cell(25, 5, number_format($item->getPrice() * $item->getQuantity(), 2, ',', ' '), 0, 0, 'R');

			if ($this->settings->getRoundingType() === 1) {
				$this->totalPrice += $item->getPrice() * $item->getQuantity();
			} else {
				$this->totalPrice += round($item->getPrice() * $item->getQuantity(), 2);
			}
		}

		$y = $y2 + $this->settings->getItemSpacing();
	}

	/**
	 * Renders VAT summary table
	 *
	 * @param array<int|string, float> $vatBaseTotal VAT base totals by rate
	 * @param array<int|string, float> $vatTotal VAT totals by rate
	 */
	private function renderVatSummary(float &$y, array $vatBaseTotal, array $vatTotal, bool $isRounded): void {
		$this->SetFont($this->settings->getFont(), 'B', 7.5);

		$this->SetXY(39, $y + 5);
		$this->Cell(27, 5, Translator::t('tax_base'), 0, 0, 'R');
		$this->Cell(22, 5, Translator::t('vat_amount'), 0, 0, 'R');
		$this->Cell(26, 5, Translator::t('total'), 0, 0, 'R');

		$this->SetLineWidth(0.1);
		$this->SetDrawColor(153, 153, 153);
		$this->Line(10.2, $y + 10, 115, $y + 10);

		$y += 11;
		$this->SetFont($this->settings->getFont(), '', 7.5);

		$totals = [0, 0, 0];

		foreach ($this->settings->getVatRates() as $rate => $label) {
			$vatAmount = $vatTotal[$rate] ?? 0;

			if ((string) $rate === '0') {
				$vatAmount = 0;
			}

			$baseAmount = $vatBaseTotal[$rate] ?? 0;

			// Display rate if base is not zero (with tolerance for rounding errors) or if summaryEmpty is enabled
			if (abs($baseAmount) > 0.001 || $this->settings->getSummaryEmpty()) {
				$this->SetXY(10, $y);
				$this->Cell(26.5, 5, $label, 0, 0, 'L');
				$this->Cell(10, 5, $rate . ' %', 0, 0, 'R');
				$this->Cell(19.5, 5, number_format($baseAmount, 2, ',', ' '), 0, 0, 'R');
				$this->Cell(22, 5, number_format($vatAmount, 2, ',', ' '), 0, 0, 'R');
				$this->Cell(26, 5, number_format($baseAmount + $vatAmount, 2, ',', ' '), 0, 0, 'R');

				$totals[0] += $baseAmount;
				$totals[1] += $vatAmount;
				$totals[2] += $baseAmount + $vatAmount;

				$y += 5;
			}
		}

		$this->SetFont($this->settings->getFont(), 'B', 7.5);
		$this->Line(10.2, $y + 1, 115, $y + 1);
		$this->SetDrawColor(0, 0, 0);
		$y += 2;
		$this->SetXY(10, $y);
		$this->Cell(30, 5, Translator::t('total_final'), 0, 0, 'L');
		$this->Cell(26.5, 5, number_format($totals[0], 2, ',', ' '), 0, 0, 'R');
		$this->Cell(22, 5, number_format($totals[1], 2, ',', ' '), 0, 0, 'R');
		$this->Cell(26, 5, number_format($totals[2], 2, ',', ' '), 0, 0, 'R');

		$this->SetLineWidth(0.3);
		$this->Line(10.2, $y + 6, 115, $y + 6);
		$this->SetLineWidth(0.2);

		$y += 5;

		if ($isRounded) {
			$this->SetXY(10, $y + 1);
			$this->SetFont($this->settings->getFont(), '', 7.5);
			$this->Cell(26, 5, Translator::t('including_rounding'), 0, 0, 'L');
		}
	}

	/**
	 * Renders totals section
	 */
	private function renderTotals(float $yLastItem, float $xOffset, bool $showDiscount): void {
		$this->SetFont($this->settings->getFont(), 'B', 10);
		$yLastItem += 0.25;
		$xCoord = 118 - $xOffset;
		$y = $yLastItem;

		// Render discount line if applicable
		if ($showDiscount) {
			$this->setXY($xCoord, $yLastItem);

			$discount = $this->settings->getDiscount();
			if ($discount[1] === 1) {
				$this->Cell(80, 5, Translator::t('discount'), 0);
				$this->SetXY(140 - $xOffset - 1, $yLastItem);
				$this->Cell(60, 5, number_format($discount[0], 2, ',', ' ') . ' %', 0, 0, 'R');
			} else {
				$this->Cell(
					80,
					5,
					$this->settings->getRoundTo() > 0 ? Translator::t('discount_rounded') : Translator::t('discount'),
					0,
				);
				$this->SetXY(140 - $xOffset - 1, $yLastItem);
				$discountAmount = round(
					$this->settings->getRoundTo() * $discount[0],
					$this->settings->getRoundingEnabled(),
				) / ($this->settings->getRoundTo() > 0 ? $this->settings->getRoundTo() : 1);
				$this->Cell(
					60,
					5,
					number_format($discountAmount, 2, ',', ' ') . ' ' . $this->settings->getCurrency(),
					0,
					0,
					'R',
				);

				// Adjust total if discount shown only at bottom
				if ($discount[2] === 1) {
					$this->totalPrice -= $discountAmount;
				}
			}

			$y += 7;
		} else {
			--$y;
			$yLastItem -= 7;
		}

		// Sum of items
		$this->setCellPaddings(0, 0, 0, 0);
		$this->SetXY($xCoord, $yLastItem + 7);
		$this->SetFont($this->settings->getFont(), 'B', 10);
		$itemCountText = $this->settings->getDisplayItemCount() ? ' (' . $this->itemCount . ')' : '';
		$this->Cell($xCoord, 5, Translator::t('items_subtotal') . $itemCountText . ':', 0);
		$this->SetXY(140 - $xOffset - 1, $yLastItem + 7);
		$this->Cell(
			60,
			5,
			number_format($this->totalPrice, 2, ',', ' ') . ' ' . $this->settings->getCurrency(),
			0,
			0,
			'R',
		);

		// Deposits
		$this->SetXY($xCoord, $yLastItem + 14);
		$this->Cell(41, 5, Translator::t('paid_advances'), 0, 0, 'L');
		$this->SetXY(140 - $xOffset - 1, $yLastItem + 14);
		$this->Cell(
			60,
			5,
			number_format($this->settings->getDeposits(), 2, ',', ' ') . ' ' . $this->settings->getCurrency(),
			0,
			0,
			'R',
		);

		// Total to pay
		$this->SetXY($xCoord, $yLastItem + 22);
		$style = $this->settings->getStyle();
		$this->SetFillColor(
			$style['pricesFillColor'][0],
			$style['pricesFillColor'][1],
			$style['pricesFillColor'][2],
		);
		$this->SetTextColor(
			$style['pricesFontColor'][0],
			$style['pricesFontColor'][1],
			$style['pricesFontColor'][2],
		);
		$this->Rect($xCoord, $yLastItem + 20, 82, 9, 'F', $this->settings->getBorders());
		$this->setCellPaddings(1, 0, 1, 0);
		$this->Cell(41, 5, Translator::t('total_to_pay'), 0, 0, 'L');
		$this->SetXY(140 - $xOffset, $yLastItem + 22);

		$finalAmount = $this->totalPrice - $this->settings->getDeposits();

		if ($this->settings->getDeposits() > 0.5 && abs($finalAmount) < 0.5) {
			$this->Cell(60, 5, number_format(0, 2, ',', ' ') . ' ' . $this->settings->getCurrency(), 0, 0, 'R');
		} else {
			$roundedAmount = round(
				$this->settings->getRoundTo() * $finalAmount,
				$this->settings->getRoundingEnabled(),
			) / ($this->settings->getRoundTo() > 0 ? $this->settings->getRoundTo() : 1);
			$this->Cell(60, 5, number_format($roundedAmount, 2, ',', ' ') . ' ' . $this->settings->getCurrency(), 0, 0, 'R');
		}

		$this->setCellPaddings(0, 0, 0, 0);
	}

	/**
	 * Renders footer section with signature line, EET info, etc.
	 *
	 * @param float $y Y position to start footer
	 */
	private function renderFooter(float $y = 0): void {
		$this->SetTextColor(0, 0, 0);

		if ($y === 0.0) {
			$y = $this->GetY();
		}

		// Display "ALREADY PAID" if applicable
		if (
			$this->settings->getDeposits() > 0 &&
			($this->totalPrice - $this->settings->getDeposits()) < 0.5
		) {
			$this->SetXY(120, $y + 8);
			$this->SetFont($this->settings->getFont(), 'B', 11);
			$this->Cell(80, 5, Translator::t('already_paid_do_not_pay'), 0, 0, 'R');
		}

		// Reverse charge notice
		if ($this->settings->getReverseCharge()) {
			$this->SetFont($this->settings->getFont(), 'B', 7);
			$this->SetXY(15, $y + 5);
			$reverseChargeText = $this->settings->getReverseChargeText() !== ''
				? $this->settings->getReverseChargeText()
				: Translator::t('reverse_charge_notice');
			$this->MultiCell(100, 0, $reverseChargeText, 0, 'L', false);
			$y = $this->GetY() - 10;
		}

		// Additional information for credit notes/corrections
		$additionalInfo = $this->settings->getAdditionalInfo();
		if (
			($this->settings->getDocumentType() === 3 || $this->settings->getDocumentType() === 4) &&
			count($additionalInfo) > 0
		) {
			$this->SetFont($this->settings->getFont(), 'B', 7);
			$this->SetXY(15, $y + 5);
			$this->Cell(0, 10, Translator::t('additional_information'));
			$this->SetFont($this->settings->getFont(), '', 7);
			$y += 10;
			$this->SetXY(15, $y);

			if (
				isset($additionalInfo['original_document'])
				&& !empty($additionalInfo['original_document'])
			) {
				switch ($this->settings->getDocumentType()) {
					case 3:
						// Credit note/correction
						if ($this->settings->getVatPayer()) {
							$this->Cell(95, 10, Translator::t('corrective_document_for_invoice') . $additionalInfo['original_document']);
						} else {
							$this->Cell(95, 10, Translator::t('credit_note_for_invoice') . $additionalInfo['original_document']);
						}

						break;
					case 4:
						// Cancellation
						$this->Cell(95, 10, Translator::t('cancellation_for_invoice') . $additionalInfo['original_document']);

						break;
				}

				$y += 7;
			}

			if (isset($additionalInfo['reason']) && !empty($additionalInfo['reason'])) {
				$this->SetXY(15, $y);

				if ($this->settings->getDocumentType() === 3) {
					$this->MultiCell(100, 0, Translator::t('correction_reason') . $additionalInfo['reason'], 0, 'L', false);
				} else {
					$this->MultiCell(100, 0, $additionalInfo['reason'], 0, 'L', false);
				}

				$y = $this->GetY() + 2;
			} else {
				$y += 2;
			}

			$this->SetLineWidth(0.3);
			$this->Line(10.2, $y, 115, $y);
			$this->SetLineWidth(0.2);
			$y -= 8;
		}

		// Signature line
		$this->signatureY = $y + 35;
		$this->dashedLine(120, $y + 35, 190, 30);
		$this->SetXY(120, $y + 35);
		$this->SetFont($this->settings->getFont(), '', 7);
		$this->Cell(70, 5, Translator::t('stamp_and_signature'), 0, 0, 'C');

		// Signature text
		$signatureText = $this->settings->getSignatureText();
		if ($signatureText !== []) {
			$currentY = $y + 10;

			foreach ($signatureText as $signatureTextItem) {
				if ($signatureTextItem[0] !== '') {
					$this->SetXY(15, $currentY);
					$this->SetFont(
						$this->settings->getFont(),
						$signatureTextItem[2],
						$signatureTextItem[1],
					);
					$this->MultiCell(95, $signatureTextItem[1] - 4, $signatureTextItem[0], 0, 'L', false);
					$currentY = $this->GetY();
				}
			}
		}

		// EET information
		$eet = $this->settings->getEet();
		if ($eet !== [] && (isset($eet['eet']) || isset($eet['fik']))) {
			$this->SetXY(15, $this->GetY() + 2);
			$this->SetFont($this->settings->getFont(), 'B', 10);
			$this->Cell(180, 5, Translator::t('electronic_sales_registry'), 0, 0, 'L');
			$this->SetY($this->GetY() + 5);
			$this->SetFont($this->settings->getFont(), '', 7);

			if (isset($eet['provozovna'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('establishment') . '</strong>: ' . $eet['provozovna'], 0, 1);
			}

			if (isset($eet['pokladna'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('cash_register') . '</strong>: ' . $eet['pokladna'], 0, 1);
			}

			if (isset($eet['datum'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('date_and_time') . '</strong>: ' . date('d.m.Y H:i:s', (int) $eet['datum']), 0, 1);
			}

			if (isset($eet['rezim'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('mode') . '</strong>: ' . $eet['rezim'], 0, 1);
			}

			if (isset($eet['fik'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('fik_code') . '</strong>: ' . $eet['fik'], 0, 1);
			}

			if (isset($eet['bkp'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('bkp_code') . '</strong>: ' . $eet['bkp'], 0, 1);
			}

			if (isset($eet['pkp'])) {
				$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . Translator::t('pkp_code') . '</strong>: ' . $eet['pkp'], 0, 1);
			}

			// Additional custom EET fields
			foreach ($eet as $key => $value) {
				if (!in_array($key, ['eet', 'provozovna', 'pokladna', 'datum', 'rezim', 'fik', 'bkp', 'pkp'], true)) {
					$this->writeHTMLCell(180, 4, 15, $this->GetY(), '<strong>' . $key . '</strong>: ' . $value, 0, 1);
				}
			}
		}

		// QR Payment in footer (if page = 'PA')
		$qrPayment = $this->settings->getQrPayment();
		if (
			!$this->alreadyPaid
			&& $qrPayment['display']
			&& $qrPayment['page'] === 'PA'
		) {
			$this->renderQRPayment($qrPayment['x'], $this->GetY() + (float) $qrPayment['y']);
		}
	}

	/**
	 * Renders QR payment code
	 */
	private function renderQRPayment(float $x, float $y): void {
		$accountNumber = $this->paymentDetails->getAccountNumber();
		$variableSymbol = $this->paymentDetails->getVariableSymbol();
		$constantSymbol = $this->paymentDetails->getConstantSymbol();
		$specificSymbol = $this->paymentDetails->getSpecificSymbol();

		$qrData = Iban::getQRString([
			'iban' => str_replace(' ', '', (string) $accountNumber[1]),
			'bic' => '',
			'amount' => (string) $this->calculateTotal(),
			'vs' => (string) ($variableSymbol[1] ?? ''),
			'ks' => (string) ($constantSymbol[1] ?? ''),
			'ss' => (string) ($specificSymbol[1] ?? ''),
		]);

		if ($qrData !== null) {
			$qrPayment = $this->settings->getQrPayment();
			$this->write2DBarcode($qrData, 'QRCODE,L', $x, $y, $qrPayment['size'], $qrPayment['size']);
		}
	}

	/**
	 * Renders address block
	 */
	private function renderAddress(Address $address, float $x, float $y, float $fontSize, bool $adjustY = false): void {
		$output = '';
		$skipped = false;
		$properties = $address->getProperties();
		$keys = array_keys($properties);
		$lastKey = end($keys);

		foreach ($properties as $key => $value) {
			// Determine separator
			$separator = $key === 'postalCode' ? ' ' : "\n";

			if (trim($value) !== '') {
				// Handle special formatting for contact info
				switch ($key) {
					case 'companyId':
						$value = Translator::t('company_id') . '       ' . $value;

						break;
					case 'taxId':
						$value = Translator::t('vat_id') . '     ' . $value;

						break;
					case 'email':
						$value = Translator::t('email') . ' ' . $value;

						break;
					case 'phone':
						$value = Translator::t('phone') . '    ' . $value;

						break;
					case 'web':
						$value = Translator::t('website') . '    ' . $value;

						break;
				}

				// Handle separator lines (marked as "--")
				if ($value === '--') {
					if (!$skipped) {
						$output .= $separator;
						$skipped = true;
					} else {
						$skipped = false;
					}
				} else {
					$output .= $value . $separator;
					$skipped = false;
				}
			}

			if ($key === $lastKey) {
				break;
			}
		}

		$this->SetFont($this->settings->getFont(), '', $fontSize);
		$this->SetXY($x, $y);
		$this->MultiCell(0, 4, $output);

		if ($adjustY) {
			if ($this->GetY() > $this->yOffset) {
				$this->yOffset = $this->GetY();
			}
		}
	}

	/**
	 * Renders information or payment details section
	 *
	 * @return float Final Y position (height used)
	 */
	private function renderInfoSection(
		Information|PaymentDetails $section,
		float $x,
		float $y,
		float $fontSize,
		float $spacing,
	): float {
		$i = 1;
		$this->SetXY($x, $y);
		$properties = $section->getProperties();

		foreach ($properties as $key => $property) {
			// Set bold font for important fields
			if ($key === 'dueDate' || $key === 'variableSymbol') {
				$this->SetFont($this->settings->getFont(), 'B', $fontSize);
			} else {
				$this->SetFont($this->settings->getFont(), '', $fontSize);
			}

			$this->SetX($x);

			if (isset($property[1])) {
				// Check if property should be displayed
				$shouldDisplay = true;

				if (isset($property[2]) && $property[2]) {
					// Property requires VAT payer status
					$shouldDisplay = $this->settings->getVatPayer();
				}

				if ($shouldDisplay) {
					// Render label and value
					foreach ($property as $index => $value) {
						if ($index === 2) {
							break; // Skip the display flag
						}

						$this->Cell(0, 5, (string) $value, 0, 1);
						$this->SetXY($x + $spacing, $y + ($i - 1) * 5);
					}

					$this->SetXY($x + $spacing, $y + $i * 5);
					$i++;
				}
			}
		}

		return $i * 5;
	}
}
